# name: Deploy to render my fist app

# on:
#   push:
#     branches: [ main ]


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to production
#         uses: johnbeynon/render-deploy-action@v0.0.8
#         with:
#           service-id: ${{ secrets.RENDER_SERVICE_ID }}
#           api-key: ${{ secrets.RENDER_API_KEY }}
#           wait-for-success: true



name: Deploy to Render - My First App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Deploy to Render (if tests pass)
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

